spring :
  application.name : eureka-reg
server :
  port : 8899
eureka :
  instance :
    hostname : localhost
  client:
    #强制不注册到注册服务器
    register-with-eureka : false
    fetch-reMsgistry : false
    serviceUrl :
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
  server :
    #（设为false，关闭自我保护主要）
    enable-self-preservation : true
    #清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms : 2000
security :
  basic :
    enabled : true
  user :
    name : admin
    password : admin