server:
  tomcat.uri-encoding : utf-8
  port : 9999
###########################################################thymeleaf######################################################
spring :
  application.name : hjj-webapp-ui
  thympersonRatioWeekeleaf :
    mode  : HTML5
    encoding :  UTF-8
    content-type :  text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache : false
  jmx.enabled : false
  activiti:
    ####校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false
  ###########################################################jdbc######################################################
  datasource :
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/wf_data?useUniscode=true&useSSL=false&autoReconnect=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
    username  : root
    password  : Local_123456
     # 初始化大小，最小，最大
    initialSize : 10
    minIdle : 10
    maxActive : 10
    # 配置获取连接等待超时的时间
    maxWait : 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis : 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters : stat,log4j
    logSlowSql : true
    ###########################################################redis######################################################
    redis:
          database: 0
          host: 127.0.0.1
          port: 6379
          password:
          timeout: 100000 # 连接超时
          pool:
              maxIdle: 10   #最大空闲连接
              max-active: 8   # 最大连接数
              max-wait: -1  # 最大等待时间（使用负值表示没有限制）
              min-idle: 0   # 连接池最小空闲连接
  ###########################################################mybatis######################################################
type-aliases-package : com.scgxdz.model
mybatis :
  mapperLocations : classpath:mapper/**/*.xml
 ###########################################################通用mapper######################################################
mapper:
    #mappers 多个接口时逗号隔开
    mappers : com.scgxdz.mapper.SupperMapper
    not-empty : false
    identity : MYSQL
###########################################################ribbon-consumer######################################################

eureka :
  instance:
  #//租期更新时间间隔（默认30秒）
          leaseRenewalIntervalInSeconds: 10
    #      //租期到期时间（默认90秒）
          leaseExpirationDurationInSeconds: 30
  #//开启健康检查（需要spring-boot-starter-actuator依赖）
  healthcheck :
    enabled : true

  client :
    registry-fetch  : true
    #缓存清单时间
    registry-fetch-interval-seconds : 30
    serviceUrl  :
#      defaultZone : http://192.168.0.150:8891/eureka/
     defaultZone : http://127.0.0.1:8899/eureka/
###########################################################log######################################################
logging :
  config : classpath:logback.xml
############业务初始化参数 结束#########################
hystrix :
  config :
    stream :
      maxConcurrentConnections: 500
      #Hystrix是否启用超时时间
  command :
    default:
      execution:
        timeout:
          enabled:  true;
          #Hystrix断路器的超时时间，默认是1s
        isolation :
          thread:
            timeoutInMilliseconds: 1990000
feign:
  hystrix :
    enabled:
      false
security :
  basic :
    enabled : true
  user :
    name : admin
    password : admin