server:
  tomcat.uri-encoding : utf-8
  port : 8090
###########################################################thymeleaf######################################################
spring :
  application.name : fushan-police
  thymeleaf :
    mode  : HTML5
    encoding :  UTF-8
    content-type :  text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache : false
  jmx.enabled : false
  activiti:
    ####校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false
###########################################################jdbc######################################################
  datasource :
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://10.50.141.246:3306/jiadun-demo-yantai?useUniscode=true&amp;useSSL=false&amp;autoReconnect=true&amp;characterEncoding=UTF-8&amp;useOldAliasMetadataBehavior=true
    username  : root
    password  : 6ygdCf?R!k.2
     # 初始化大小，最小，最大
    initialSize : 2
    minIdle : 10
    maxActive : 100
    # 配置获取连接等待超时的时间
    maxWait : 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis : 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements : true
    maxPoolPreparedStatementPerConnectionSize : 20
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters : stat,wall,log4j
    logSlowSql : true


###########################################################redis######################################################
  redis:
        database: 0
        host: 10.50.141.246
        port: 6379
        password: 1
        timeout: 100000 # 连接超时
        pool:
            maxIdle: 10   #最大空闲连接
            max-active: 8   # 最大连接数
            max-wait: -1  # 最大等待时间（使用负值表示没有限制）
            min-idle: 0   # 连接池最小空闲连接

###########################################################mybatis######################################################

#mybatis.config-locations : classpath:mybatis/mybatis-config.xml
#mybatis.mapper-locations : classpath:mybatis/mapper/*.xml
type-aliases-package : com.jiadun.model
mybatis :
  mapperLocations : classpath:mapper/*.xml
 # config-location : classpath:mybatis/mybatis-config.xml
 # 分页插件(slave)
 ###########################################################通用mapper######################################################
mapper:
    #mappers 多个接口时逗号隔开
    mappers: com.jiadun.utils.MyMapper
    not-empty: false
    identity: MYSQL
###########################################################ribbon-consumer######################################################
eureka :
  instance:
  #//租期更新时间间隔（默认30秒）
          leaseRenewalIntervalInSeconds: 10
    #      //租期到期时间（默认90秒）
          leaseExpirationDurationInSeconds: 30
  #//开启健康检查（需要spring-boot-starter-actuator依赖）
  healthcheck :
    enabled : true

  client :
    registry-fetch  : true
    #缓存清单时间
    registry-fetch-interval-seconds : 30
    serviceUrl  :
      defaultZone : http://10.50.141.246:8899/eureka/
      #defaultZone : http://112.112.70.46:8899/eureka/

###########################################################log######################################################
logging :
  config : classpath:logback.xml
    #level : com.jiadun.dao=DEBUG

###########################################################dfs######################################################

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:
    width: 150
    height: 150
  trackerList:
     112.112.4.166:8081
   # 10.2.1.190:22122
  webServerUrl : http://112.112.4.166:8081/
###########################################################system param######################################################
REDIS_LOGIN_SURVIVALTIME : 7200
SERVER_URL : http://10.50.141.246:8080/ #图片存储才用
web.upload-path : /opt/upImgTmp/
#spring.mvc.static-path-pattern=/**
#spring.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

#ROOTPATH_UP_IMG : /opt/upImgTmp/
SERVER_MAIN_ID : 1 #服务器主版本号
SERVER_SUB_ID : 2 #服务器次版本号
FILE_MAX: 50 #文件大小单位兆
CLIENTIP: 192.168.2.32:8080 #暂时不用
URL :
  bigDBURL : bigdata
   #192.168.49.155:8888 # peer1:8888
########################################--电脑锁屏与解锁----开始----############################################################
lockornulock:
  port: 8080
  LOCK: LOCKSCR
  UNLOCK: UNLOCKSCR
  PS_LIST: PSLIST
  PC_INFO: PCINFO
########################################--电脑锁屏与解锁----结束----############################################################

############业务初始化参数 开始#########################
BUSINNESS:
  # 笔录类型
  recordType:
    1: 询问笔录
    2: 讯问笔录
  # 继电器的端口
  relayPort: 8899
############业务初始化参数 结束#########################
hystrix :
  config :
    stream :
      maxConcurrentConnections: 500
      #Hystrix是否启用超时时间
  command :
    default:
      execution:
        timeout:
          enabled:  true;
          #Hystrix断路器的超时时间，默认是1s
        isolation :
          thread:
            timeoutInMilliseconds: 1999000
feign:
  hystrix :
    enabled:
      false