############################################################server.port######################################################
server  :
  tomcat  :
    uri-encoding : utf-8
  port : 9005
###########################################################spring.boot.admin.url######################################################
spring:
  application:
    name: zuul-server
  boot  :
      admin :
        url : http://localhost:9002
###########################################################注册中心######################################################
eureka :
  instance:
  #//租期更新时间间隔（默认30秒）
          leaseRenewalIntervalInSeconds: 10
    #      //租期到期时间（默认90秒）
          leaseExpirationDurationInSeconds: 30
  #//开启健康检查（需要spring-boot-starter-actuator依赖）
  healthcheck :
    enabled : true

  client :
    registry-fetch  : true
    #缓存清单时间
    registry-fetch-interval-seconds : 30
    serviceUrl  :
     defaultZone : http://localhost:9003/eureka/
###########################################################management.security.enabled=false########################################
management :
  security  :
    enabled : false
###########################################################zuul######################################################
#zuul  :
#  routes  :
#    #保障态势
#    hjj_assure_server :
#      path  : /hjj_assure_serv/**
#      serviceId : HJJ_ASSURE_SERVER
#     #任务态势
#    hjj_task_server :
#     path  : /hjj_task_server/**
#     serviceId : HJJ_TASK_SERV
#    #维修保障
#     hjj_repair_server :
#       path  : /hjj_repair_serv/**
#       serviceId : HJJ_REPAIR_SERV
#    #装备态势
#     hjj_equipment_server :
#       path  : /hjj_equipment_serv/**
#       serviceId : HJJ_EQUIPMENT_SERV
#    #综合态势
#     hjj_synthesize_server :
#       path  : /hjj_synthesize_serv/**
#       serviceId : HJJ_SYNTHESIZE_SERV
###########################################################log######################################################
logging :
  config : classpath:logback.xml
  level :
    tk :
      mybatis :
        TRACE
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"