############################################################server.port######################################################
server  :
  tomcat  :
    uri-encoding : utf-8
  port : 9007
###########################################################spring.boot.admin.url######################################################
spring:
  application:
    name: turbine-server
###########################################################注册中心######################################################
eureka :
  instance:
  #//租期更新时间间隔（默认30秒）
          leaseRenewalIntervalInSeconds: 10
    #      //租期到期时间（默认90秒）
          leaseExpirationDurationInSeconds: 30
  #//开启健康检查（需要spring-boot-starter-actuator依赖）
  healthcheck :
    enabled : true

  client :
    registry-fetch  : true
    #缓存清单时间
    registry-fetch-interval-seconds : 30
    serviceUrl  :
     defaultZone : http://localhost:9003/eureka/

###########################################################turbine######################################################
turbine:
  app-config  : sleuth-server
  clusterNameExpression: "'default'"
###########################################################log######################################################
logging :
  config : classpath:logback.xml
  level :
    tk :
      mybatis :
        TRACE
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"