############################################################server.port######################################################
server  :
  tomcat  :
    uri-encoding : utf-8
  port : 9001
###########################################################spring.boot.admin.url######################################################
spring:
  application:
    name: sleuth_server
  boot  :
      admin :
        url : http://localhost:9002
###########################################################链路信息保存数据库中mysql config######################################################
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.112:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
###########################################################sleuth######################################################
  sleuth:
    sampler:
      percentage: 1.0
    enabled: false
  ##########################################################spring.rabbitmq##########################################################
  rabbitmq :
    addresses : 192.168.0.114:5672
    username  : admin
    password  : admin
    publisher-confirms  : true
    virtual-host  : /
###########################################################注册中心######################################################
eureka :
  instance:
  #//租期更新时间间隔（默认30秒）
          leaseRenewalIntervalInSeconds: 10
    #      //租期到期时间（默认90秒）
          leaseExpirationDurationInSeconds: 30
  #//开启健康检查（需要spring-boot-starter-actuator依赖）
  healthcheck :
    enabled : true

  client :
    registry-fetch  : true
    #缓存清单时间
    registry-fetch-interval-seconds : 30
    serviceUrl  :
     defaultZone : http://localhost:9003/eureka/

###########################################################zipkin.storage.type######################################################
zipkin:
  storage:
    type: mysql

###########################################################management.security.enabled=false########################################
management :
  security  :
    enabled : false
###########################################################log######################################################
logging :
  config : classpath:logback.xml
  level :
    tk :
      mybatis :
        TRACE
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"