server  :
  tomcat  :
    uri-encoding : utf-8
  port : 9001
###########################################################spring.boot.admin.url######################################################
spring :
  application :
    name : Sleuth_Server
  boot  :
    admin :
      url : http://localhost:9002
###########################################################链路信息保存数据库中mysql config######################################################
  datasource  :
    schema  : classpath:/mysql.sql
    url : jdbc:mysql://192.168.0.112:3306/test
    username  : root
    password  : 123456
    initialize  : true
    continueOnError  : true
  sleuth  :
    enabled : true
  ##########################################################spring.rabbitmq##########################################################
  rabbitmq :
      addresses : 192.168.0.114:5672
      username  : admin
      password  : admin
      publisher-confirms  : true
      virtual-host  : /
###########################################################注册中心######################################################
eureka  :
  server  :
    #设为false，关闭自我保护
    enable-self-preservation  : false
  client  :
    registerWithEureka  : false #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry  : false  #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl  :
      defaultZone : http://localhost:9003/eureka/
############################################################zipkin.storage.type#####################################################
zipkin  :
  storage :
    type  : mysql
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"
###########################################################management.security.enabled=false########################################
management :
  security  :
    enabled : false

###########################################################elasticsearch config#####################################################
###########################################################log######################################################
logging :
  config : classpath:logback.xml
  level :
    tk :
      mybatis :
        TRACE